defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  # uri: mongodb://admin:yentaballs@flame.mongohq.com:27058/yenta-development
  uri: mongodb://heroku:e2ac170b7e3f6489f591d11108389b60@staff.mongohq.com:10014/app4106841
  # uri: mongodb://yenta:yentaballs@staff.mongohq.com:10079/yenta-staging

test:
  <<: *defaults
  database: yenta-friend_test

# set these environment variables on your prod server
production:
  # uri: mongodb://yenta:yentaballs@staff.mongohq.com:10079/yenta-staging
  uri: <%=ENV['MONGOHQ_URL'] %>