defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  uri: mongodb://root:password@staff.mongohq.com:10009/till_dawn

test:
  <<: *defaults
  database: yenta-friend_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>    
