defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  uri: mongodb://yenta:yentaballs@staff.mongohq.com:10079/yenta-staging

test:
  <<: *defaults
  database: yenta-friend_test

# set these environment variables on your prod server
production:
  uri: mongodb://yenta:yentaballs@staff.mongohq.com:10079/yenta-staging
