development:
  access_key_id: AKIAICZOJNDMXYASZLUA
  secret_access_key: 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
  bucket: yenta-friend-development
test:
  access_key_id: AKIAICZOJNDMXYASZLUA
  secret_access_key: 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
  bucket: yenta-friend-test
production:
  access_key_id: AKIAICZOJNDMXYASZLUA
  secret_access_key: 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
  bucket: yenta-friend
